
Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [2]:
import numpy as np; arr = np.ones((10, 10)); arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [4]:
import numpy as np

chessboard = np.indices((8, 8)).sum(axis=0) % 2
chessboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные

In [5]:
import numpy as np

matrix = np.diag([1,2,3,4], k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [11]:
import numpy as np
array = np.random.rand(5, 5)
array_normalized = array - array.mean(axis=1, keepdims=True)
array_normalized
print(array_normalized.mean(axis=1))

[-5.55111512e-18 -2.22044605e-17  2.22044605e-17  4.44089210e-17
 -4.44089210e-17]


5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [13]:
closest_to_half = np.apply_along_axis(lambda row: row[np.abs(row - 0.5).argmin()], 1, np.random.rand(10, 3))
closest_to_half

array([0.72059124, 0.47006798, 0.43489652, 0.53609737, 0.58681824,
       0.63067432, 0.7204156 , 0.44584065, 0.48247428, 0.42453069])

6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [17]:
result = np.sum(array := np.random.rand(6, 6), axis=1) / np.max(array, axis=0)
result

array([3.65063109, 4.68810271, 4.38049831, 4.0187875 , 3.4658726 ,
       3.56776969])

7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [23]:
import numpy as np

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max_elem = x[np.where(x[:-1] == 0)[0] + 1].max()
max_elem


5

8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [27]:
import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at(x, i, 1)
x

array([2., 2., 2., 2., 1., 4., 1., 1., 2., 1.])